<a href="https://colab.research.google.com/github/S3IFK/Practise/blob/main/Keras_Tuner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('diabetes.csv')

In [5]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [7]:
X = df.iloc[:, :-1].values
y = df.iloc[:,-1].values

In [8]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [9]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler()

In [12]:
X = scaler.fit_transform(X)

In [13]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [14]:
X.shape

(768, 8)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [17]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [18]:
model = Sequential()

In [19]:
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(24,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [20]:
model.fit(X_train,y_train, batch_size=32,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
20/20 [==============================] - 1s 17ms/step - loss: 0.7034 - accuracy: 0.5407 - val_loss: 0.6936 - val_accuracy: 0.6039
Epoch 2/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6319 - accuracy: 0.6971 - val_loss: 0.6366 - val_accuracy: 0.6818
Epoch 3/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5787 - accuracy: 0.7557 - val_loss: 0.5929 - val_accuracy: 0.7078
Epoch 4/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5395 - accuracy: 0.7687 - val_loss: 0.5659 - val_accuracy: 0.7013
Epoch 5/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5093 - accuracy: 0.7720 - val_loss: 0.5494 - val_accuracy: 0.7273
Epoch 6/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4885 - accuracy: 0.7704 - val_loss: 0.5367 - val_accuracy: 0.7532
Epoch 7/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4742 - accuracy: 0.7801 - val_loss: 0.5262 - val_accuracy: 0.7727
Epoch 8/100


In [21]:
from keras.layers import Dropout

In [22]:
model1 = Sequential()
model1.add(Dense(32,activation='relu',input_dim=8))
model.add(Dropout(0.2))
model1.add(Dense(24,activation='relu'))
model.add(Dropout(0.2))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [23]:
model1.fit(X_train,y_train,batch_size=32,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
20/20 [==============================] - 1s 14ms/step - loss: 0.6748 - accuracy: 0.6042 - val_loss: 0.6558 - val_accuracy: 0.6169
Epoch 2/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5955 - accuracy: 0.6759 - val_loss: 0.6141 - val_accuracy: 0.6558
Epoch 3/100
20/20 [==============================] - 0s 5ms/step - loss: 0.5514 - accuracy: 0.6987 - val_loss: 0.5926 - val_accuracy: 0.6688
Epoch 4/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5211 - accuracy: 0.7296 - val_loss: 0.5754 - val_accuracy: 0.6688
Epoch 5/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4987 - accuracy: 0.7378 - val_loss: 0.5619 - val_accuracy: 0.6883
Epoch 6/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4827 - accuracy: 0.7492 - val_loss: 0.5545 - val_accuracy: 0.7273
Epoch 7/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4710 - accuracy: 0.7671 - val_loss: 0.5482 - val_accuracy: 0.7273
Epoch 8/100


In [24]:
pip install -U keras-tuner

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.1/176.1 kB 4.5 MB/s eta 0:00:00


In [25]:
import kerastuner as kt

<ipython-input-25-5fd8096cdee5>:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt


In [26]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(32,activation='relu',input_dim=8))
  model.add(Dense(24,activation='relu'))
  model.add(Dense(1,activation='sigmoid'))

  optimizer = hp.Choice('optimizer',values = ['adam', 'sgd', 'rmsprop','adadelta'])

  model.compile(optimizer=optimizer, loss= 'binary_crossentropy',metrics=['accuracy'])

  return model

In [27]:
tuner = kt.RandomSearch(build_model, objective='val_accuracy',max_trials=10)

In [28]:
tuner.search(X_train,y_train,epochs=10,validation_data=(X_test,y_test))

Trial 4 Complete [00h 00m 07s]
val_accuracy: 0.5259740352630615

Best val_accuracy So Far: 0.7792207598686218
Total elapsed time: 00h 00m 18s


In [29]:
tuner.results_summary()

Results summary
Results in ./untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 01 summary
Hyperparameters:
optimizer: rmsprop
Score: 0.7792207598686218

Trial 02 summary
Hyperparameters:
optimizer: adam
Score: 0.7792207598686218

Trial 00 summary
Hyperparameters:
optimizer: sgd
Score: 0.7142857313156128

Trial 03 summary
Hyperparameters:
optimizer: adadelta
Score: 0.5259740352630615


In [30]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [31]:
modeln = tuner.get_best_models(num_models=1)[0]

In [32]:
modeln.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 24)                792       
                                                                 
 dense_2 (Dense)             (None, 1)                 25        
                                                                 
Total params: 1,105
Trainable params: 1,105
Non-trainable params: 0
_________________________________________________________________


In [33]:
modeln.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=10,validation_data=(X_test,y_test))

Epoch 11/100
20/20 [==============================] - 2s 14ms/step - loss: 0.4734 - accuracy: 0.7785 - val_loss: 0.5021 - val_accuracy: 0.7662
Epoch 12/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4623 - accuracy: 0.7736 - val_loss: 0.5028 - val_accuracy: 0.7662
Epoch 13/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4547 - accuracy: 0.7769 - val_loss: 0.5037 - val_accuracy: 0.7662
Epoch 14/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4487 - accuracy: 0.7834 - val_loss: 0.5068 - val_accuracy: 0.7662
Epoch 15/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4438 - accuracy: 0.7801 - val_loss: 0.5068 - val_accuracy: 0.7662
Epoch 16/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4397 - accuracy: 0.7932 - val_loss: 0.5067 - val_accuracy: 0.7662
Epoch 17/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4367 - accuracy: 0.7883 - val_loss: 0.5070 - val_accuracy: 0.7662
Epoch

In [34]:
def build_model(hp):
  model = Sequential()

  units = hp.Int('units', min_value =8, max_value=128)

  model.add(Dense(units=units,activation='relu',input_dim=8))
  model.add(Dense(units=units, activation='relu'))
  model.add(Dense(1,activation='sigmoid'))


  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [35]:
tuner= kt.RandomSearch(build_model, objective= 'val_accuracy',max_trials=5,directory='my_dir',project_name='hrk')

In [36]:
tuner.search(X_train,y_train,epochs=10,validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.7857142686843872

Best val_accuracy So Far: 0.798701286315918
Total elapsed time: 00h 00m 18s


In [37]:
tuner.results_summary()

Results summary
Results in my_dir/hrk
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 2 summary
Hyperparameters:
units: 41
Score: 0.798701286315918

Trial 0 summary
Hyperparameters:
units: 109
Score: 0.7857142686843872

Trial 4 summary
Hyperparameters:
units: 59
Score: 0.7857142686843872

Trial 3 summary
Hyperparameters:
units: 19
Score: 0.7662337422370911

Trial 1 summary
Hyperparameters:
units: 93
Score: 0.7597402334213257


In [38]:
tuner.get_best_hyperparameters()[0].values

{'units': 41}

In [39]:
def build_model(hp):
  model = Sequential()

  model.add(Dense(72,activation='relu',input_dim=8))

  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
    model.add(Dense(72,activation='relu'))

  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='rmsprop', loss='binary_crossentropy',metrics=['accuracy'])

  return model

In [40]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy', max_trials=3, directory='my_dir',project_name='gig')

In [41]:
tuner.search(X_train,y_train,epochs=10,validation_data=(X_test, y_test))

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.7727272510528564

Best val_accuracy So Far: 0.7922077775001526
Total elapsed time: 00h 00m 10s


In [42]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 7}