<a href="https://colab.research.google.com/github/S3IFK/Practise/blob/main/NewCodesPractise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
kg2ws = lambda kg: kg*1000
print(kg2ws(5))

5000


In [ ]:
evenodd = lambda num: True if num%2 ==0 else False

In [ ]:
evenodd(2)

True

In [ ]:
evenodd = lambda num: num%2 ==0

In [ ]:
print(evenodd(5))
print(evenodd(4))

False
True


In [ ]:
s = lambda x,y: x+y

In [ ]:
s(4,5)

9

In [ ]:
numlist=[1,2,3,4,5,6,7,8,9]

#map
print(map(lambda x: x**2, numlist))

In [ ]:
print(list(map(lambda x: x**3, numlist)))
print(set(map(lambda x: x**2, numlist)))
print(tuple(map(lambda x: x**3, numlist)))

[1, 8, 27, 64, 125, 216, 343, 512, 729]
{64, 1, 4, 36, 9, 16, 49, 81, 25}
(1, 8, 27, 64, 125, 216, 343, 512, 729)


In [ ]:
usr_in = input('Enter some intergers with space separated: ')
print(usr_in)
usr_split = usr_in.split()
print(usr_split)
print(list(map(int, usr_split)))

Enter some intergers with space separated: 1 2 3 4 5
1 2 3 4 5
['1', '2', '3', '4', '5']
[1, 2, 3, 4, 5]


In [ ]:
print(list(map(int, input('Enter some number: ').split())))

Enter some number: 1 2 3
[1, 2, 3]


In [ ]:
print(list(filter(lambda num: num%2 ==0, numlist)))

[2, 4, 6, 8]


In [ ]:
gtbox = ['bread','iph*one','buter','ip*ad','milk']

In [ ]:
print(list(filter(lambda x: '*' in x, gtbox)))

['iph*one', 'ip*ad']


In [ ]:
#reduce
from functools import reduce

In [ ]:
print(reduce(lambda x,y: x+y, numlist))

45


In [ ]:
def Funcsum(x,y):
  print(f'x is {x}; y is {y}; Sum of it is {x+y}')
  return x+y

print(reduce(Funcsum ,numlist))

x is 1; y is 2; Sum of it is 3
x is 3; y is 3; Sum of it is 6
x is 6; y is 4; Sum of it is 10
x is 10; y is 5; Sum of it is 15
x is 15; y is 6; Sum of it is 21
x is 21; y is 7; Sum of it is 28
x is 28; y is 8; Sum of it is 36
x is 36; y is 9; Sum of it is 45
45


In [ ]:
print(reduce(lambda x,y: x if x<y else y, numlist))

1


In [ ]:
nums = list(map(int, input('Enter some number: ').split()))
num2 = list(filter(lambda n: n%2==0, nums))
print(reduce(lambda x,y: x+y, num2))

Enter some number: 1 2 3 4 5 6
12


In [ ]:
nums = list(map(int, input('Enter some number: ').split()))
print(nums)

Enter some number: 1 2 3 4 5 6 7 8
[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
num2 = list(filter(lambda n: n%2==0, nums))
print(num2)

[2, 4, 6, 8]


In [ ]:
print(reduce(lambda x,y: x+y, num2))

20


In [ ]:
my_list = [100,200,2 , 'Ronaldo', False]

In [ ]:
print(my_list, type(my_list))

[100, 200, 2, 'Ronaldo', False] <class 'list'>


In [ ]:
my_list= [100,200,300,40]
print([x+1 for x in my_list])

[101, 201, 301, 41]


In [1]:
my_lst = [1,2,3,4,5,6]
type(my_lst)

list

In [8]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
arr = np.array([1,2,3,4,5,6.2])
print(arr, arr.dtype)

[1.  2.  3.  4.  5.  6.2] float64


In [5]:
arr = np.array([1,2,3,"4",5,6.2])
print(arr, type(arr))

['1' '2' '3' '4' '5' '6.2'] <class 'numpy.ndarray'>


In [7]:
arr.dtype

dtype('<U32')

In [19]:
my_list = [[1,2,3],[4,5,6],[8,9,10]]

In [20]:
art = np.array(my_list)

In [21]:
print(art)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [22]:
print(art.shape)

(3, 3)


In [33]:
print(my_list[1])

[4, 5, 6]


In [35]:
print(art[2][2])

print(art[1,2])

10
6


In [37]:
my_list[2][0] = 8.2

print(my_list)

[[1, 2, 3], [4, 5, 6], [8.2, 9, 10]]


In [46]:
art[2,0] = 8.23

In [47]:
print(art)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [52]:
arm = np.arange(0,11,5)
print(arm)

[ 0  5 10]


In [54]:
arr = np.zeros((5,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [55]:
from numpy.core.memmap import dtype
arr = np.zeros((5,4), dtype = int)
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [56]:
arr = np.ones((5,4))
print(arr)


arr = np.ones((5,4), dtype = int)
print(arr)



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [59]:
## linearly spaced data
arg = np.linspace(1,7,10)
print(arg)

anm = np.linspace(1,7,20)
print(anm)

[1.         1.66666667 2.33333333 3.         3.66666667 4.33333333
 5.         5.66666667 6.33333333 7.        ]
[1.         1.31578947 1.63157895 1.94736842 2.26315789 2.57894737
 2.89473684 3.21052632 3.52631579 3.84210526 4.15789474 4.47368421
 4.78947368 5.10526316 5.42105263 5.73684211 6.05263158 6.36842105
 6.68421053 7.        ]


In [62]:
agm = np.eye(10)
print(agm)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
