<a href="https://colab.research.google.com/github/S3IFK/Practise/blob/main/NewCodesPractise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
import pandas as pd

In [26]:
kg2ws = lambda kg: kg*1000
print(kg2ws(5))

5000


In [27]:
evenodd = lambda num: True if num%2 ==0 else False

In [28]:
evenodd(2)

True

In [29]:
evenodd = lambda num: num%2 ==0

In [30]:
print(evenodd(5))
print(evenodd(4))

False
True


In [31]:
s = lambda x,y: x+y

In [32]:
s(4,5)

9

In [33]:
numlist=[1,2,3,4,5,6,7,8,9]

#map
print(map(lambda x: x**2, numlist))

In [34]:
print(list(map(lambda x: x**3, numlist)))
print(set(map(lambda x: x**2, numlist)))
print(tuple(map(lambda x: x**3, numlist)))

[1, 8, 27, 64, 125, 216, 343, 512, 729]
{64, 1, 4, 36, 9, 16, 49, 81, 25}
(1, 8, 27, 64, 125, 216, 343, 512, 729)


In [35]:
usr_in = input('Enter some intergers with space separated: ')
print(usr_in)
usr_split = usr_in.split()
print(usr_split)
print(list(map(int, usr_split)))

Enter some intergers with space separated: 1 3 4 6 7 8
1 3 4 6 7 8
['1', '3', '4', '6', '7', '8']
[1, 3, 4, 6, 7, 8]


In [36]:
print(list(map(int, input('Enter some number: ').split())))

Enter some number: 5 6  7 8
[5, 6, 7, 8]


In [37]:
print(list(filter(lambda num: num%2 ==0, numlist)))

[2, 4, 6, 8]


In [38]:
gtbox = ['bread','iph*one','buter','ip*ad','milk']

In [39]:
print(list(filter(lambda x: '*' in x, gtbox)))

['iph*one', 'ip*ad']


In [40]:
#reduce
from functools import reduce

In [41]:
print(reduce(lambda x,y: x+y, numlist))

45


In [42]:
def Funcsum(x,y):
  print(f'x is {x}; y is {y}; Sum of it is {x+y}')
  return x+y

print(reduce(Funcsum ,numlist))

x is 1; y is 2; Sum of it is 3
x is 3; y is 3; Sum of it is 6
x is 6; y is 4; Sum of it is 10
x is 10; y is 5; Sum of it is 15
x is 15; y is 6; Sum of it is 21
x is 21; y is 7; Sum of it is 28
x is 28; y is 8; Sum of it is 36
x is 36; y is 9; Sum of it is 45
45


In [43]:
print(reduce(lambda x,y: x if x<y else y, numlist))

1


In [45]:
nums = list(map(int, input('Enter some number: ').split()))
num2 = list(filter(lambda n: n%2==0, nums))
print(reduce(lambda x,y: x+y, num2))

Enter some number: 1 2 3 4 5
6


In [46]:
nums = list(map(int, input('Enter some number: ').split()))
print(nums)

Enter some number: 1 2 3 4 
[1, 2, 3, 4]


In [47]:
num2 = list(filter(lambda n: n%2==0, nums))
print(num2)

[2, 4]


In [48]:
print(reduce(lambda x,y: x+y, num2))

6


In [49]:
my_list = [100,200,2 , 'Ronaldo', False]

In [50]:
print(my_list, type(my_list))

[100, 200, 2, 'Ronaldo', False] <class 'list'>


In [51]:
my_list= [100,200,300,40]
print([x+1 for x in my_list])

[101, 201, 301, 41]


In [52]:
my_lst = [1,2,3,4,5,6]
type(my_lst)

list

In [53]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
arr = np.array([1,2,3,4,5,6.2])
print(arr, arr.dtype)

[1.  2.  3.  4.  5.  6.2] float64


In [54]:
arr = np.array([1,2,3,"4",5,6.2])
print(arr, type(arr))

['1' '2' '3' '4' '5' '6.2'] <class 'numpy.ndarray'>


In [55]:
arr.dtype

dtype('<U32')

In [56]:
my_list = [[1,2,3],[4,5,6],[8,9,10]]

In [57]:
art = np.array(my_list)

In [58]:
print(art)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [59]:
print(art.shape)

(3, 3)


In [60]:
print(my_list[1])

[4, 5, 6]


In [61]:
print(art[2][2])

print(art[1,2])

10
6


In [62]:
my_list[2][0] = 8.2

print(my_list)

[[1, 2, 3], [4, 5, 6], [8.2, 9, 10]]


In [63]:
art[2,0] = 8.23

In [64]:
print(art)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [65]:
arm = np.arange(0,11,5)
print(arm)

[ 0  5 10]


In [66]:
arr = np.zeros((5,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [67]:
from numpy.core.memmap import dtype
arr = np.zeros((5,4), dtype = int)
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [68]:
arr = np.ones((5,4))
print(arr)


arr = np.ones((5,4), dtype = int)
print(arr)



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [69]:
## linearly spaced data
arg = np.linspace(1,7,10)
print(arg)

anm = np.linspace(1,7,20)
print(anm)

[1.         1.66666667 2.33333333 3.         3.66666667 4.33333333
 5.         5.66666667 6.33333333 7.        ]
[1.         1.31578947 1.63157895 1.94736842 2.26315789 2.57894737
 2.89473684 3.21052632 3.52631579 3.84210526 4.15789474 4.47368421
 4.78947368 5.10526316 5.42105263 5.73684211 6.05263158 6.36842105
 6.68421053 7.        ]


In [70]:
agm = np.eye(10)
print(agm)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [71]:

import numpy as np
import pandas as pd
akm = np.random.rand(1,7)

In [72]:
print(akm)

[[0.01655923 0.78871958 0.55937986 0.04525314 0.78065332 0.3440828
  0.02022768]]


In [73]:
akm = np.random.randint(1,100,(10,1))
print(akm)


[[44]
 [45]
 [95]
 [90]
 [99]
 [81]
 [14]
 [74]
 [45]
 [30]]


In [74]:
print(akm.reshape(1,10))

[[44 45 95 90 99 81 14 74 45 30]]


In [75]:
print(akm.sum())

617


In [76]:
print(arm.sum())

15


In [77]:
print(agm.sum())

10.0


In [78]:
print(akm.sum(axis=0))

[617]


In [81]:
print(arm.sum(axis=0))

15
