<a href="https://colab.research.google.com/github/S3IFK/Practise/blob/main/NewCodesPractise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
import pandas as pd

In [26]:
kg2ws = lambda kg: kg*1000
print(kg2ws(5))

5000


In [27]:
evenodd = lambda num: True if num%2 ==0 else False

In [28]:
evenodd(2)

True

In [29]:
evenodd = lambda num: num%2 ==0

In [30]:
print(evenodd(5))
print(evenodd(4))

False
True


In [31]:
s = lambda x,y: x+y

In [32]:
s(4,5)

9

In [33]:
numlist=[1,2,3,4,5,6,7,8,9]

#map
print(map(lambda x: x**2, numlist))

In [34]:
print(list(map(lambda x: x**3, numlist)))
print(set(map(lambda x: x**2, numlist)))
print(tuple(map(lambda x: x**3, numlist)))

[1, 8, 27, 64, 125, 216, 343, 512, 729]
{64, 1, 4, 36, 9, 16, 49, 81, 25}
(1, 8, 27, 64, 125, 216, 343, 512, 729)


In [35]:
usr_in = input('Enter some intergers with space separated: ')
print(usr_in)
usr_split = usr_in.split()
print(usr_split)
print(list(map(int, usr_split)))

Enter some intergers with space separated: 1 3 4 6 7 8
1 3 4 6 7 8
['1', '3', '4', '6', '7', '8']
[1, 3, 4, 6, 7, 8]


In [36]:
print(list(map(int, input('Enter some number: ').split())))

Enter some number: 5 6  7 8
[5, 6, 7, 8]


In [37]:
print(list(filter(lambda num: num%2 ==0, numlist)))

[2, 4, 6, 8]


In [38]:
gtbox = ['bread','iph*one','buter','ip*ad','milk']

In [39]:
print(list(filter(lambda x: '*' in x, gtbox)))

['iph*one', 'ip*ad']


In [40]:
#reduce
from functools import reduce

In [41]:
print(reduce(lambda x,y: x+y, numlist))

45


In [42]:
def Funcsum(x,y):
  print(f'x is {x}; y is {y}; Sum of it is {x+y}')
  return x+y

print(reduce(Funcsum ,numlist))

x is 1; y is 2; Sum of it is 3
x is 3; y is 3; Sum of it is 6
x is 6; y is 4; Sum of it is 10
x is 10; y is 5; Sum of it is 15
x is 15; y is 6; Sum of it is 21
x is 21; y is 7; Sum of it is 28
x is 28; y is 8; Sum of it is 36
x is 36; y is 9; Sum of it is 45
45


In [43]:
print(reduce(lambda x,y: x if x<y else y, numlist))

1


In [45]:
nums = list(map(int, input('Enter some number: ').split()))
num2 = list(filter(lambda n: n%2==0, nums))
print(reduce(lambda x,y: x+y, num2))

Enter some number: 1 2 3 4 5
6


In [46]:
nums = list(map(int, input('Enter some number: ').split()))
print(nums)

Enter some number: 1 2 3 4 
[1, 2, 3, 4]


In [47]:
num2 = list(filter(lambda n: n%2==0, nums))
print(num2)

[2, 4]


In [48]:
print(reduce(lambda x,y: x+y, num2))

6


In [49]:
my_list = [100,200,2 , 'Ronaldo', False]

In [50]:
print(my_list, type(my_list))

[100, 200, 2, 'Ronaldo', False] <class 'list'>


In [51]:
my_list= [100,200,300,40]
print([x+1 for x in my_list])

[101, 201, 301, 41]


In [1]:
my_lst = [1,2,3,4,5,6]
type(my_lst)

list

In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
arr = np.array([1,2,3,4,5,6.2])
print(arr, arr.dtype)

[1.  2.  3.  4.  5.  6.2] float64


In [3]:
arr = np.array([1,2,3,"4",5,6.2])
print(arr, type(arr))

['1' '2' '3' '4' '5' '6.2'] <class 'numpy.ndarray'>


In [4]:
arr.dtype

dtype('<U32')

In [5]:
my_list = [[1,2,3],[4,5,6],[8,9,10]]

In [6]:
art = np.array(my_list)

In [7]:
print(art)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [8]:
print(art.shape)

(3, 3)


In [9]:
print(my_list[1])

[4, 5, 6]


In [10]:
print(art[2][2])

print(art[1,2])

10
6


In [11]:
my_list[2][0] = 8.2

print(my_list)

[[1, 2, 3], [4, 5, 6], [8.2, 9, 10]]


In [12]:
art[2,0] = 8.23

In [13]:
print(art)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [14]:
arm = np.arange(0,11,5)
print(arm)

[ 0  5 10]


In [15]:
arr = np.zeros((5,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
from numpy.core.memmap import dtype
arr = np.zeros((5,4), dtype = int)
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [17]:
arr = np.ones((5,4))
print(arr)


arr = np.ones((5,4), dtype = int)
print(arr)



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [18]:
## linearly spaced data
arg = np.linspace(1,7,10)
print(arg)

anm = np.linspace(1,7,20)
print(anm)

[1.         1.66666667 2.33333333 3.         3.66666667 4.33333333
 5.         5.66666667 6.33333333 7.        ]
[1.         1.31578947 1.63157895 1.94736842 2.26315789 2.57894737
 2.89473684 3.21052632 3.52631579 3.84210526 4.15789474 4.47368421
 4.78947368 5.10526316 5.42105263 5.73684211 6.05263158 6.36842105
 6.68421053 7.        ]


In [19]:
agm = np.eye(10)
print(agm)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [20]:

import numpy as np
import pandas as pd
akm = np.random.rand(1,7)

In [21]:
print(akm)

[[0.16540313 0.31714124 0.39925908 0.20996987 0.30029474 0.49424677
  0.86106534]]


In [22]:
akm = np.random.randint(1,100,(10,1))
print(akm)


[[36]
 [34]
 [74]
 [28]
 [64]
 [53]
 [46]
 [20]
 [30]
 [52]]


In [23]:
print(akm.reshape(1,10))

[[36 34 74 28 64 53 46 20 30 52]]


In [24]:
print(akm.sum())

437


In [25]:
print(arm.sum())

15


In [26]:
print(agm.sum())

10.0


In [27]:
print(akm.sum(axis=0))

[437]


In [28]:
print(arm.sum(axis=0))

15


In [29]:
print(akm.mean(axis=0))

[43.7]


In [30]:
print(arm.mean(axis=0))

5.0


In [39]:
print(np.linspace(1,20,20, dtype=int))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [42]:
print(np.linspace(1,20,20, dtype=int).reshape(2,10))

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [43]:
arr = np.arange(10)

In [46]:
print(arr)

print(arr>5)

print(arr[arr>4])

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True  True  True  True]
[5 6 7 8 9]


In [48]:
arj = np.arange(10)

print(arj%2==0)

print(arj[arj%2==0])

[ True False  True False  True False  True False  True False]
[0 2 4 6 8]


In [50]:
lst = list(range(1,11))
arr= np.arange(1,11)
print(lst)
print(arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [51]:
print(lst+lst)
print(arr+arr)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 2  4  6  8 10 12 14 16 18 20]


In [53]:
##print(lst-lst)
print(arr-arr)

[0 0 0 0 0 0 0 0 0 0]


In [55]:
##print(lst*lst)
print(arr*arr)  

[  1   4   9  16  25  36  49  64  81 100]


In [56]:
print(arr/arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [57]:
print(arr%arr)

[0 0 0 0 0 0 0 0 0 0]


In [59]:
print(lst*2)
print(arr*2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 2  4  6  8 10 12 14 16 18 20]


In [61]:
print(arr**(1/2))
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


In [65]:
print(np.log(arr))
print(np.sin(arr))
print(np.cos(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]


In [66]:
print(np.where(arr ==6))

(array([5]),)


In [67]:
hkm = np.random.randint(-99,99,10)
print(hkm)

[ -2  60 -27 -14  93 -46  49  46   0 -93]


In [68]:
print(np.sort(hkm))

[-93 -46 -27 -14  -2   0  46  49  60  93]


In [70]:
print(~np.sort(hkm))

[ 92  45  26  13   1  -1 -47 -50 -61 -94]


In [73]:
print(np.vstack((hkm,hkm)))

[[ -2  60 -27 -14  93 -46  49  46   0 -93]
 [ -2  60 -27 -14  93 -46  49  46   0 -93]]


In [74]:
print(np.hstack((hkm,hkm)))

[ -2  60 -27 -14  93 -46  49  46   0 -93  -2  60 -27 -14  93 -46  49  46
   0 -93]


In [79]:
print(np.isnan(arr).sum(axis=0))

0
